export const CATALOGO = [
  {
    id: "wpc-decking",
    nombreOriginal: "WPC Decking 30x30",
    queryBusqueda: "deck wpc encastrable 30x30",
    palabrasProhibidas: ["zocalo", "zócalo", "perfil", "colocacion", "colocación", "instalacion", "muestra"],
    palabrasObligatorias: ["wpc", "deck"],
    precioMin: 3000,
    precioMax: 60000,
  },
  {
    id: "flexible-stone",
    nombreOriginal: "Flexible Stone Tiles",
    queryBusqueda: "revestimiento piedra flexible 120x60",
    palabrasProhibidas: ["pegamento", "adhesivo", "muestra", "fragua", "sellador"],
    palabrasObligatorias: ["piedra", "flexible", "revestimiento"],
    precioMin: 5000,
    precioMax: 80000,
  },
  {
    id: "spc-plank-4mm",
    nombreOriginal: "SPC Plank Floor 4mm",
    queryBusqueda: "piso vinilico spc 4mm",
    palabrasProhibidas: ["zocalo", "zócalo", "manta", "varilla", "colocacion", "colocación", "rodapie", "rodapié"],
    palabrasObligatorias: ["spc", "piso", "4mm"],
    precioMin: 10000,
    precioMax: 50000,
  },
  {
    id: "pvc-marble-sheet",
    nombreOriginal: "PVC Marble Sheet",
    queryBusqueda: "placa revestimiento pvc marmol",
    palabrasProhibidas: ["perfil", "adhesivo", "muestra", "fragua", "sellador", "pegamento"],
    palabrasObligatorias: ["pvc", "placa", "revestimiento"],
    precioMin: 3000,
    precioMax: 70000,
  },
  {
    id: "aluminum-profile",
    nombreOriginal: "Aluminum Alloy Profile",
    queryBusqueda: "perfil aluminio terminacion 3m",
    palabrasProhibidas: ["tira led", "policarbonato", "tornillo", "kit", "soporte"],
    palabrasObligatorias: ["perfil", "aluminio"],
    precioMin: 2000,
    precioMax: 50000,
  },
];